---
title:  |
    | Environmental and Development Economics
    | Week 1 - Introduction
author:
  |
    | Raahil Madhok
    | UMN Applied Economics
date: "`r Sys.Date()`"

# Output type and options (no TOC and yes fig captions)
output: 
  beamer_presentation:
    theme: Montpellier
classoption: "aspectratio=169"

# This includes latex arguments
header-includes:
  - \AtBeginDocument{\title[Week 1 - Introduction]{\textbf{Environmental and Development Economics} \\ Week 1 - Introduction}}
  - \input{header.tex}

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, dev = "png") # NOTE: switched to png instead of pdf to decrease size of the resulting pdf
```

# Introduction

## Introduce yourself

- First, lets do introductions
\vfill

- Name, year, memorable summer activity, **research interests**
\vfill

- Why are you taking this class?

## Today

\vfill
- Course overview
\vfill
- Detailed outline
\vfill
- Grade breakdown
\vfill
- Course website on github: https://github.com/rmadhok/enviro-dev-grad
  - lecture slides, assignments, syllabus
  
\vfill

## 

\centering
\huge Course Overview

## Course Overview: There is no textbook

Instead, I am organizing around **\textcolor{orange}{FOUR}** key questions:

1. Why is environmental quality so bad in developing countries?

2. What are the costs of poor environmental quality in developing countries?

3. Why is WTP for environmental quality low in developing countries?

4. What are the political economy barriers to environmental protection?

## Course Approach

I will:

- Frame (almost) each topic with some theory

- Teach applied papers
  - research design, identification strategy, estimation techniques

- Emphasize recent JMPs

\vfill

I will NOT:

- Teach econometrics

- Teach coding

- Teach every topic in environment/development

## Course Goals

For students specializing in environment/development: 

1. Show you research frontier

2. Inspire your thesis/JMP ideas

\vfill

For other students:

3. Advance your training as applied microeconomists

4. Show you what makes a top-tier research question


## Course Structure

- This is a brand new class, so I give myself leeway to make changes
\vfill
- You have the unique opportunity to determine direction of the course
  - Think about what topics do and don't interest you
  - And let me know!
\vfill
- Please check the course website regularly for updates

## 

\centering
\huge Course Outline and Topics

## Weeks 1 and 2

**Week 1: Theory of Environment/Development**

- How to use theory to ask the right questions (lecture 2)

\vfill 

**Week 2: The effect of development on the environment**

- air quality, water quality (lecture 3)
- forests, biodiversity (lecture 4)

## Weeks 3 and 4

**Week 3: The effect of the environment on development**

- human capital (lecture 5)
- firms (lecture 6)

\vfill 

**Week 4: WTP for Environmental Quality**

- TBD (lecture 7)
- TBD (lecture 8)

## Weeks 5, 6, and 7

**Week 5: Environmental policy design**

- Spillovers (lecture 9)
- Pollution markets in developing countries (lecture 10)

\vfill 

**Week 6: Political economy of the environment**

- Corruption and weak enforcement  (lecture 11)
- Environmental justice (lecture 12)

\vfill

**Week 7: Research presentations**

- I will provide more details throughout the semester

## 

\centering
\huge Grade Breakdown

## Broad Breakdown

\Large 

\begin{table}[]
\begin{tabular}{lllll}
In-class presentations      & 10\% &  &  &  \\
Problem Set           & 20\% &  &  &  \\
Research Proposal & 60 \% &  &  &  \\
Participation                     & 10\%     &  &  & 
\end{tabular}
\end{table}

## In-class presentations (10%)

- At start of each lecture (from week 2), you will present a paper for 15 minutes

- Each student reads paper and submits **seven** slides (5% of grade)
  - motivation, research question, methods, results
  - 10 mins presentation + 5 mins Q&A (5% of grade)
  
- I will select presenter **randomly** with replacement**

\vfill 

** \footnotesize If you are never chosen, your grade is based on slides. 


## Problem Set (20%)

- You will replicate an environment/development paper
  - You will also **extend** the results

- You will become familiar with coding in publication-quality papers

- You will use R or Stata

## Research Proposal (60%)

\begin{table}[]
\begin{tabular}{lllll}
Written Proposal      & 30\% &  &  &  \\
Peer Review           & 20\% &  &  &  \\
Proposal Presentation & 10\% &  &  &  \\
                      &      &  &  & 
\end{tabular}
\end{table}


- You will develop a research proposal for an original idea
  - You are NOT expected to actually do the analysis  
  - I will provide small deadlines (outline, first draft, etc.) along the way

- You will peer review each others proposals

- You will present the proposal at the end of the semester (30 mins)

## Participation (10%)

- I take this seriously

- Not enough to just show up to class

- Quality of questions/discussion count


##

\centering
\Huge Questions?

## Next class

\vfill

- Introduce conceptual framework of environment/development economics









